package com.expandenegocio.veonegocio.models;

import java.util.Date;

/**
 * Created by jesus on 28/04/2017.
 */

public enum ClavesFranquicia {

    NAME,
    ID,
    DESCRIPTION,
    INDUSTRY,
    PHONE_OFFICE,
    PHONE_ALTERNATE,
    WEBSITE,
    OWNERSHIP,
    EMPLOYEES,
    TIPO_FICHA,
    ZONA,
    LOGOTIPO,
    VIDEO,
    EXCLUSION_DE_SECTOR,
    EXCLUSION_DE_SUBSECTOR,
    ESTADO_VALIDACION,
    TIPO_DE_FRANQUICIADO,
    NECESARIO_TITULACION,
    TITULACION,
    CONDICIONES_ESPECIALES,
    FIN_CONDICIONES_ESPECIALES,
    OBSERVACIONES,
    INVERSION_MINIMA_NECESARIA,
    CURRENCY_ID,
    TIPO_FRANQUICIA,
    NECESITA_LOCAL,
    SUPERFICIE_LOCAL,
    REQUISITOS_LOCAL,
    ENTORNO_UBICACION,
    OBSERVACIONES_UBICACION,
    POBLACION_MINIMA,
    PERSONAL_MINIMO,
    ZONA_EXCLISIVA,
    VIGENCIA_CONTRATO,
    RECONVERTIR_NEGOCIO,
    ACUERDO_FINANCIACION,
    SECTOR,
    BREVE_DESCRIPCION,
    FECHA_CREACION,
    FECHA_EXPANSION,
    CENTROS_NACIONALES_PROPIOS,
    CENTROS_NACIONALES_FRANQUICIA,
    PRESENCIA_INTERNACIONAL,
    RED_SPAIN,
    CENTROS_EXTRANJEROS_PROPIOS,
    CENTROS_EXTRANJEROS_FRANQUI,
    RED_EXTRANGERA,
    PLANTILLA_CENTRAL,
    CIFRA_NEGOCIO_GRUPO,
    NIFRA,
    REGMARCA,
    AEF,
    SELLOS_CALIDAD,
    OTRO_SELLO_CALIDAD,
    EMPRESA,
    LOCALIDAD,
    DIRECCION_DIRECCION,
    DIRECCION_LOCALIDAD,
    DIRECCION_CODIGO_POSTAL,
    DIRECCION_PROVINCIA,
    DIRECCION_PAIS,
    PERSONA_CONTACTO,
    FECHA_ACUERDO,
    FECHA_ACTIVACION,
    FICHA_AMPLIADA_ANTERIOR,
    EXPAN_CONSULTORA_ID_C,
    ESTADO_FRAN,
    OBSERVACIONES_INTER,
    PRESELECCIONADAS,
    HOMOLOGACION,
    DOCUMENTACION_PENDIENTE,
    DERECHO_ENTRADA_MIN,
    DERECHO_ENTRADA_MAX,
    ROYALTY_EXPLTACION,
    ROYALTY_PUBLICITARIO,
    OTROS_ROYALTIES,
    FACTURACION_YEAR_UNIDAD_FRAN_1,
    FACTURACION_YEAR_UNIDAD_FRAN_2,
    FACTURACION_YEAR_UNIDAD_FRAN_3,
    AMORTIZACIO_INVERSION,
    BENEFICIO_NETO_UNIDAD_FRAN_1,
    BENEFICIO_NETO_UNIDAD_FRAN_2,
    BENEFICIO_NETO_UNIDAD_FRAN_3,
    TIPO_ACTIVIDAD;


    /**
     * @returnarcon los nombres de las claves de este enum
     */
    public static String[] claves() {
        //modifica este método
        ClavesFranquicia[] todas = ClavesFranquicia.values();
        int longitud = todas.length;
        String[] nombres = new String[longitud];
        for (int i = 0; i < longitud; i++) {
            nombres[i] = todas[i].toString();
        }
        return nombres;
    }


}